'use client'

import { useState } from 'react'
import { Check, CircleX, Copy, RotateCcw, SkipForward, Smartphone, Sparkles } from 'lucide-react'

type Status = 'pending' | 'active' | 'correct' | 'wrong' | 'passed'
type Letter = { letter: string; clue: string; answer: string; gift: string; status: Status }

const seed: Letter[] = [
  ['A', 'Algo que Elena siempre lleva en el bolso', 'abanico', 'Un detalle con mucho aire'], ['B', 'Un plan para hacer juntos', 'barco', 'Una escapada'], ['C', 'Su postre favorito', 'chocolate', 'Una caja especial'], ['D', 'Donde empezó todo', 'domingo', 'Una carta'], ['E', 'La inicial de la cumpleañera', 'elena', 'El regalo principal'], ['F', 'Una flor que le pega mucho', 'flor', 'Un ramo'], ['G', 'Algo que nunca falta en una celebración', 'globos', 'Una sorpresa decorada'], ['H', 'Un lugar para descansar', 'hotel', 'Una noche fuera'], ['I', 'Lo que hace que todo sea inolvidable', 'ilusión', 'Un recuerdo'], ['J', 'Una joya pequeña', 'joya', 'Un destello'], ['L', 'Una forma de decir te quiero', 'luz', 'Un momento a solas'], ['M', 'Su música para bailar', 'música', 'Una playlist'], ['N', 'Lo que hoy celebramos', 'nacimiento', 'Muchos años felices'], ['O', 'Un abrazo muy grande es...', 'oso', 'Un peluche'], ['P', 'Pasa palabra si no la sabes', 'pasa', 'Seguimos jugando'], ['Q', 'Algo que se hace con cariño', 'querer', 'Un beso'], ['R', 'Lo que Elena se merece hoy', 'reina', 'Un día de reina'], ['S', 'Un recuerdo que guardamos', 'sonrisa', 'Una foto'], ['T', 'Un viaje que empieza con T', 'tren', 'Billetes para dos'], ['U', 'Lo que somos cuando estamos juntos', 'uno', 'Tiempo compartido'], ['V', 'Un deseo de cumpleaños', 'vida', 'Un brindis'], ['Y', 'Un regalo hecho con...', 'yema', 'Un dulce'], ['Z', 'El final de este rosco', 'zapatillas', 'Para estrenar']].map(([letter, clue, answer, gift]) => ({ letter, clue, answer, gift, status: 'pending' }))

export function GameRoom({ mode, room }: { mode: 'screen' | 'control'; room: string }) {
  const [letters, setLetters] = useState(seed)
  const [selected, setSelected] = useState(0)
  const [spinning, setSpinning] = useState(false)
  const [config, setConfig] = useState(false)
  const current = letters[selected]

  const setStatus = (status: Status) => setLetters((items) => items.map((item, index) => index === selected ? { ...item, status } : item))
  const next = () => { setSelected((selected + 1) % letters.length); setSpinning(false) }
  const reset = () => { setLetters(seed); setSelected(0) }
  const share = () => navigator.clipboard?.writeText(`${location.origin}?mode=control&room=${room}`)

  const color = (status: Status) => status === 'correct' ? 'bg-primary text-primary-foreground border-primary' : status === 'wrong' ? 'bg-destructive text-destructive-foreground border-destructive' : status === 'passed' ? 'bg-accent text-accent-foreground border-accent' : status === 'active' ? 'border-primary text-primary' : 'border-border bg-card text-foreground'

  return <main className={`min-h-screen bg-background text-foreground ${mode === 'screen' ? 'p-6 md:p-10' : 'p-5'}`}>
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-4">
      <div><p className="font-mono text-[10px] uppercase tracking-[0.3em] text-primary">Una sorpresa para Elena</p><h1 className="mt-2 font-serif text-3xl md:text-4xl">Cumpleaños Elena</h1></div>
      <div className="flex items-center gap-2"><div className="rounded-full border border-border px-4 py-2 font-mono text-xs tracking-widest">SALA {room}</div>{mode === 'screen' && <button onClick={share} aria-label="Copiar enlace de control" className="rounded-full border border-border p-3 hover:bg-muted"><Copy size={16}/></button>}</div>
    </header>
    {mode === 'screen' ? <section className="mx-auto mt-10 grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_360px]">
      <div className="relative mx-auto flex aspect-square w-full max-w-[680px] items-center justify-center rounded-full border border-border/60 bg-card shadow-2xl shadow-primary/5"><div className="absolute inset-10 rounded-full border border-border/40"/>{letters.map((item, i) => { const angle = (360 / letters.length) * i - 90; return <button key={item.letter} onClick={() => setSelected(i)} className={`absolute flex h-12 w-12 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 text-sm font-bold transition-all md:h-16 md:w-16 md:text-xl ${color(item.status)} ${i === selected ? 'scale-125 shadow-lg shadow-primary/30' : ''}`} style={{ left: `${50 + 42 * Math.cos(angle * Math.PI / 180)}%`, top: `${50 + 42 * Math.sin(angle * Math.PI / 180)}%` }}>{item.letter}</button> })}<div className="z-10 flex h-36 w-36 flex-col items-center justify-center rounded-full bg-background text-center shadow-xl md:h-48 md:w-48"><Sparkles className="mb-2 text-primary" size={20}/><span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Ahora toca</span><strong className="mt-2 font-serif text-6xl">{current.letter}</strong></div></div>
      <div className="text-center lg:text-left"><p className="font-mono text-xs uppercase tracking-[0.25em] text-muted-foreground">Pista</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">{current.clue}</h2><p className="mt-5 text-muted-foreground">Cuando Elena acierte, descubre el regalo.</p><div className="mt-8 rounded-2xl border border-border bg-card p-5"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Código para el móvil</p><p className="mt-2 font-mono text-3xl tracking-[0.25em] text-primary">{room}</p><p className="mt-2 text-sm text-muted-foreground">Abre el mismo enlace y añade <span className="font-mono">?mode=control&room={room}</span></p></div></div>
    </section> : <section className="mx-auto max-w-lg"><div className="mt-8 rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><Smartphone className="text-primary"/><div><p className="font-semibold">Panel de control</p><p className="text-sm text-muted-foreground">Sala {room || 'sin código'}</p></div></div><label className="mt-8 block text-sm font-medium">Código de sala<input defaultValue={room} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 font-mono uppercase outline-none focus:ring-2 focus:ring-ring" placeholder="ABC123"/></label><div className="mt-8 border-t border-border pt-6"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Letra actual</p><div className="mt-3 flex items-center justify-between"><span className="font-serif text-7xl">{current.letter}</span><button onClick={next} className="rounded-full border border-border p-4 hover:bg-muted" aria-label="Siguiente letra"><SkipForward size={20}/></button></div><p className="mt-4 text-lg leading-7">{current.clue}</p><p className="mt-2 text-sm text-muted-foreground">Regalo: {current.gift}</p><div className="mt-7 grid grid-cols-3 gap-2"><button onClick={() => setStatus('correct')} className="flex flex-col items-center gap-2 rounded-2xl bg-primary px-2 py-4 text-xs font-semibold text-primary-foreground"><Check size={21}/>Acierto</button><button onClick={() => setStatus('wrong')} className="flex flex-col items-center gap-2 rounded-2xl bg-destructive px-2 py-4 text-xs font-semibold text-destructive-foreground"><CircleX size={21}/>Fallo</button><button onClick={() => setStatus('passed')} className="flex flex-col items-center gap-2 rounded-2xl border border-border px-2 py-4 text-xs font-semibold hover:bg-muted"><SkipForward size={21}/>Pasa</button></div></div><button onClick={() => setConfig(!config)} className="mt-6 w-full rounded-xl border border-border py-3 text-sm hover:bg-muted">{config ? 'Ocultar configuración' : 'Editar pistas y regalos'}</button>{config && <div className="mt-4 rounded-xl bg-muted p-4 text-sm text-muted-foreground">La configuración completa estará disponible aquí para editar cada letra, pista, respuesta y regalo.</div>}<button onClick={reset} className="mt-3 flex w-full items-center justify-center gap-2 py-3 text-sm text-muted-foreground hover:text-foreground"><RotateCcw size={15}/>Reiniciar partida</button></div></section>}
  </main>
}
